### ISSUE TITLE
Minio Server/ Client QS finalize the headings 

### ISSUE THREAD

**Issue by deekoder** [minio/docs.minio.io#30]
Has 2 install sections. Let's discuss in the team meeting and finalize this.

**Comment by GarimaKapoor** [comment]
In today's meeting it was decided that since the download link and the instructions are in different place it would be not intuitive to developers of how to install them .So we decided to break it in two different steps. What is wrong is that the step 1 should be download and step 2 should be install or install instructions.

**Comment by deekoder** [comment]
ok fixed. mc.

**Comment by deekoder** [comment]
Actually changing permissions should not be called Install. It's not really Install. Let's discuss in meeting Garima. Server and Client are mismatched in headings.

**Comment by deekoder** [comment]
This is changed and resolved.
